//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ALFA/ALFA.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System.Diagnostics.CodeAnalysis;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ALFAParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IALFAListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([Antlr4.Runtime.Misc.NotNull] ALFAParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([Antlr4.Runtime.Misc.NotNull] ALFAParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([Antlr4.Runtime.Misc.NotNull] ALFAParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([Antlr4.Runtime.Misc.NotNull] ALFAParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDcl([Antlr4.Runtime.Misc.NotNull] ALFAParser.VarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDcl([Antlr4.Runtime.Misc.NotNull] ALFAParser.VarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInAnim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltInAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInAnim"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltInAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInAnimCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltInAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInAnimCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltInAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInCreateShape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltInCreateShape([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInCreateShape"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltInCreateShape([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInCreateShapeCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltInCreateShapeCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInCreateShapeCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltInCreateShapeCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([Antlr4.Runtime.Misc.NotNull] ALFAParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([Antlr4.Runtime.Misc.NotNull] ALFAParser.TypeContext context);
}
