//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ALFA/ALFA.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using System.Diagnostics.CodeAnalysis;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IALFAListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
[ExcludeFromCodeCoverage]
public partial class ALFABaseListener : IALFAListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([Antlr4.Runtime.Misc.NotNull] ALFAParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([Antlr4.Runtime.Misc.NotNull] ALFAParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([Antlr4.Runtime.Misc.NotNull] ALFAParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([Antlr4.Runtime.Misc.NotNull] ALFAParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDcl([Antlr4.Runtime.Misc.NotNull] ALFAParser.VarDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDcl([Antlr4.Runtime.Misc.NotNull] ALFAParser.VarDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltInAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltInAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInAnimCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltInAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInAnimCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltInAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInCreateShape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltInCreateShape([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInCreateShape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltInCreateShape([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInCreateShapeCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltInCreateShapeCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInCreateShapeCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltInCreateShapeCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg([Antlr4.Runtime.Misc.NotNull] ALFAParser.ArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([Antlr4.Runtime.Misc.NotNull] ALFAParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([Antlr4.Runtime.Misc.NotNull] ALFAParser.TypeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([Antlr4.Runtime.Misc.NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([Antlr4.Runtime.Misc.NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([Antlr4.Runtime.Misc.NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([Antlr4.Runtime.Misc.NotNull] IErrorNode node) { }
}
