//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ALFA/ALFA.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using System.Diagnostics.CodeAnalysis;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IALFAListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
[ExcludeFromCodeCoverage]
public partial class ALFABaseListener : IALFAListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterProgram([Antlr4.Runtime.Misc.NotNull] ALFAParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitProgram([Antlr4.Runtime.Misc.NotNull] ALFAParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterVarDcl([Antlr4.Runtime.Misc.NotNull] ALFAParser.VarDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitVarDcl([Antlr4.Runtime.Misc.NotNull] ALFAParser.VarDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterAssignStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.AssignStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.assignStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitAssignStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.AssignStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterIfStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.IfStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.ifStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitIfStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.IfStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.loopStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterLoopStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.LoopStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.loopStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitLoopStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.LoopStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.paralStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterParalStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.ParalStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.paralStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitParalStmt([Antlr4.Runtime.Misc.NotNull] ALFAParser.ParalStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterNot([Antlr4.Runtime.Misc.NotNull] ALFAParser.NotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitNot([Antlr4.Runtime.Misc.NotNull] ALFAParser.NotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Or</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterOr([Antlr4.Runtime.Misc.NotNull] ALFAParser.OrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Or</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitOr([Antlr4.Runtime.Misc.NotNull] ALFAParser.OrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterMulDiv([Antlr4.Runtime.Misc.NotNull] ALFAParser.MulDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitMulDiv([Antlr4.Runtime.Misc.NotNull] ALFAParser.MulDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterAddSub([Antlr4.Runtime.Misc.NotNull] ALFAParser.AddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitAddSub([Antlr4.Runtime.Misc.NotNull] ALFAParser.AddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterParens([Antlr4.Runtime.Misc.NotNull] ALFAParser.ParensContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitParens([Antlr4.Runtime.Misc.NotNull] ALFAParser.ParensContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>And</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterAnd([Antlr4.Runtime.Misc.NotNull] ALFAParser.AndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>And</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitAnd([Antlr4.Runtime.Misc.NotNull] ALFAParser.AndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Num</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterNum([Antlr4.Runtime.Misc.NotNull] ALFAParser.NumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Num</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitNum([Antlr4.Runtime.Misc.NotNull] ALFAParser.NumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterRelational([Antlr4.Runtime.Misc.NotNull] ALFAParser.RelationalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitRelational([Antlr4.Runtime.Misc.NotNull] ALFAParser.RelationalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterUnaryMinus([Antlr4.Runtime.Misc.NotNull] ALFAParser.UnaryMinusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitUnaryMinus([Antlr4.Runtime.Misc.NotNull] ALFAParser.UnaryMinusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Id</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterId([Antlr4.Runtime.Misc.NotNull] ALFAParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Id</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitId([Antlr4.Runtime.Misc.NotNull] ALFAParser.IdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterEquality([Antlr4.Runtime.Misc.NotNull] ALFAParser.EqualityContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitEquality([Antlr4.Runtime.Misc.NotNull] ALFAParser.EqualityContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBoolean([Antlr4.Runtime.Misc.NotNull] ALFAParser.BooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Boolean</c>
	/// labeled alternative in <see cref="ALFAParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBoolean([Antlr4.Runtime.Misc.NotNull] ALFAParser.BooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBlock([Antlr4.Runtime.Misc.NotNull] ALFAParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBlock([Antlr4.Runtime.Misc.NotNull] ALFAParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.paralBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterParalBlock([Antlr4.Runtime.Misc.NotNull] ALFAParser.ParalBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.paralBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitParalBlock([Antlr4.Runtime.Misc.NotNull] ALFAParser.ParalBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBuiltInAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBuiltInAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInAnimCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBuiltInAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInAnimCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBuiltInAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInAnimCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInCreateShape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBuiltInCreateShape([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInCreateShape"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBuiltInCreateShape([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInCreateShapeCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBuiltInCreateShapeCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInCreateShapeCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBuiltInCreateShapeCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInCreateShapeCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInParalAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBuiltInParalAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInParalAnimContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInParalAnim"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBuiltInParalAnim([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInParalAnimContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtInParalAnimCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBuiltInParalAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInParalAnimCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtInParalAnimCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBuiltInParalAnimCall([Antlr4.Runtime.Misc.NotNull] ALFAParser.BuiltInParalAnimCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.actualParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterActualParams([Antlr4.Runtime.Misc.NotNull] ALFAParser.ActualParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.actualParams"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitActualParams([Antlr4.Runtime.Misc.NotNull] ALFAParser.ActualParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterType([Antlr4.Runtime.Misc.NotNull] ALFAParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitType([Antlr4.Runtime.Misc.NotNull] ALFAParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void EnterBool([Antlr4.Runtime.Misc.NotNull] ALFAParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	[ExcludeFromCodeCoverage]
	public virtual void ExitBool([Antlr4.Runtime.Misc.NotNull] ALFAParser.BoolContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	[ExcludeFromCodeCoverage]
	public virtual void EnterEveryRule([Antlr4.Runtime.Misc.NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	[ExcludeFromCodeCoverage]
	public virtual void ExitEveryRule([Antlr4.Runtime.Misc.NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	[ExcludeFromCodeCoverage]
	public virtual void VisitTerminal([Antlr4.Runtime.Misc.NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	[ExcludeFromCodeCoverage]
	public virtual void VisitErrorNode([Antlr4.Runtime.Misc.NotNull] IErrorNode node) { }
}
