//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ALFA/ALFA.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ALFAParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IALFAListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ALFAParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ALFAParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ALFAParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ALFAParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDcl([NotNull] ALFAParser.VarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDcl([NotNull] ALFAParser.VarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] ALFAParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] ALFAParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.builtIns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltIns([NotNull] ALFAParser.BuiltInsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.builtIns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltIns([NotNull] ALFAParser.BuiltInsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgs([NotNull] ALFAParser.ArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgs([NotNull] ALFAParser.ArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] ALFAParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] ALFAParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ALFAParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] ALFAParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ALFAParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] ALFAParser.TypeContext context);
}
